### ISSUE TITLE
RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

### ISSUE THREAD

**Issue by predawnang** [HoverBaum/meilidu-hexo#10]
I got this error after git clone https://github.com/HoverBaum/meilidu-hexo.git themes/meilidu
RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

**Comment by HoverBaum** [comment]
Was that error a result of the `git clone` or another command you ran after that?

**Comment by predawnang** [comment]
sorry for so late! I thought it was the result of git clone, and I 've already use another theme. I‘m very grateful for your comments
