### ISSUE TITLE
Some strict mode error when process ejs files.

### ISSUE THREAD

**Issue by cyishere** [HoverBaum/meilidu-hexo#8]
Hello, when I use this theme there're some errors during process <code>.ejs</code> files:

```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

My **node** version is 4.4.6, and **npm** version is 3.10.6, I don't know whether is the version issue.

How could I fix this? Thank you.

**Comment by HoverBaum** [comment]
This is an error with you Node version. The theme uses some ES6 features which are not enabled by default before Node v6.

You can refer to https://github.com/HoverBaum/meilidu-hexo/issues/3#issuecomment-239980290 for more about this.

So go ahead and update Node and that should solve it for you. Hope you enjoy the theme.

**Comment by cyishere** [comment]
Thank you.
